### ISSUE TITLE
[i18n-post] Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by genox** [wmertens/compiled-i18n#2]
Hi,

This is a weird one. Seemingly out of nowhere, the build throws an error after collecting strings. I don't exactly know what changed, it worked a few hours ago and I made sure there are no issues with ' or " that end up unescaped in the generated json. The json files are valid, no issues detected, even by a linter (other than a missing line break at the end of the file..).

Here is the full error message:

```
[i18n-post] Unexpected token ' in JSON at position 0
✓ built in 3.52s
error during build:
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Module.replaceGlobals (/projects/kilometro/node_modules/compiled-i18n/dist/transform-localize.cjs:197:22)
    at Object.generateBundle (/projects/kilometro/node_modules/compiled-i18n/dist/vite.cjs:210:42)
    at file:///Users/genox/projects/kilometro/node_modules/rollup/dist/es/shared/node-entry.js:18639:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

I have to investigate further if this has been caused by a dependency update. My project is heavily WIP so they change frequently. Happy to receive any pointers as to what might cause this. Let me know if I can provide more information.

**Comment by genox** [comment]
I think I found the culprit. Between build I added a string like this:

```
{_`Discount code "${item.code}" used`}
```

This was extracted JSON as 

```
"Discount code \"$1\" used"
```

This seemingly looks fine in JSON but causes the `JSON.parse()` in `transform-localise.ts` to throw an error in `replaceGlobals()`.

**Comment by wmertens** [comment]
Ah yes hmm :( the problem is that I can't tell Babel how to format the string, and it normally makes double quoted strings.

Not sure how I'll tackle this, PRs welcome.

In the meantime, I propose you keep the keys short and simple, it's better to do the fancy translations inside the translation files.

**Comment by genox** [comment]
I had a look at it but I don't quite know where to start with something like babel, to be honest. :) One idea that went thru my head was that it might be an option to hash the keynames in translation files and in the code before trying to match/replace, as this could probably circumvent any formatting and escaping issues altogether but .. well. it sure isn't elegant, nor performant. The robustness would improve, tho. As long as it only affects the keys and we assume that they are always static.. But since it is only relevant during compilation, it might be an option to pre-emptively solve all kinds of key issues as well. Would also entail setting a default value based on the key used in code on the extracted base language tho.
